// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Data;

#nullable disable

namespace MovieWebApp.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20241130131356_SeededDirector3")]
    partial class SeededDirector3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieApp.DataModels.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7caabdf8-3e3e-467f-a6ec-2536ecd974d8"),
                            ActorImageUrl = "https://images.fandango.com/ImageRenderer/300/0/redesign/static/img/default_poster.png/0/images/masterrepository/performer%20images/132947/BradleyCooper-2022_r.jpg",
                            Description = "Bradley Cooper is a highly acclaimed American actor and filmmaker known for his versatility and dedication to his craft. He was born on January 5, 1975, in Philadelphia, Pennsylvania. Over the years, he has established himself as one of the most talented and bankable stars in Hollywood.",
                            FirstName = "Bradley",
                            Surname = "Cooper"
                        },
                        new
                        {
                            Id = new Guid("6fb97c94-407e-4f2d-87aa-3374cfd8aa86"),
                            ActorImageUrl = "https://i0.gmx.ch/image/610/39010610,pd=1,f=sdata11/colman-domingo.jpg",
                            Description = "Colman Domingo is an acclaimed American actor, playwright, and director known for his versatile performances across theater, film, and television. Born on November 28, 1969, in Philadelphia, Pennsylvania, he has built a career marked by powerful storytelling and emotional depth.",
                            FirstName = "Colman",
                            Surname = "Domingo"
                        },
                        new
                        {
                            Id = new Guid("85fb8611-6ec4-4f7b-bc2f-ee958c7caa12"),
                            ActorImageUrl = "https://s.abcnews.com/images/GMA/240222_gma_digital_paul_giamatti_hpMain_4x5_608.jpg",
                            Description = "Paul Giamatti is a celebrated American actor known for his versatility and compelling performances in both leading and supporting roles. Born on June 6, 1967, in New Haven, Connecticut, he has built a distinguished career across film, television, and theater.",
                            FirstName = "Paul",
                            Surname = "Giamatti"
                        },
                        new
                        {
                            Id = new Guid("b7771af3-23ef-4bd3-9316-f3d906b7c376"),
                            ActorImageUrl = "https://m.media-amazon.com/images/M/MV5BMTM3OTUwMDYwNl5BMl5BanBnXkFtZTcwNTUyNzc3Nw@@._V1_.jpg",
                            Description = "Scarlett Johansson is an award-winning American actress and singer, widely regarded as one of the most talented and versatile performers of her generation. Born on November 22, 1984, in New York City, she has achieved immense success in both independent films and blockbuster franchises.",
                            FirstName = "Scarlett",
                            Surname = "Johansson"
                        },
                        new
                        {
                            Id = new Guid("a082cc32-c860-44ee-a538-380b0441c5dd"),
                            ActorImageUrl = "https://i.pinimg.com/736x/b0/86/f1/b086f106f5f95f68df6d86b8fab10b6d.jpg",
                            Description = "Cillian Murphy is an Irish actor renowned for his intense performances and transformative roles across film, television, and theater. Born on May 25, 1976, in Douglas, County Cork, Ireland, Murphy is celebrated for his versatility and ability to portray complex, nuanced characters.",
                            FirstName = "Cillian",
                            Surname = "Murphy"
                        });
                });

            modelBuilder.Entity("MovieApp.DataModels.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd059468-7094-4933-8686-c96a7fe1af64"),
                            CountryImageUrl = "https://cdn.britannica.com/33/4833-050-F6E415FE/Flag-United-States-of-America.jpg",
                            Description = "The U.S. film industry, centered in Hollywood, is the largest and most influential in the world, known for its high-budget productions and global reach. It produces a diverse range of films, from independent projects to blockbuster franchises like Star Wars and the Marvel Cinematic Universe. As a cultural powerhouse, it shapes global trends in storytelling, technology, and entertainment.",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("d3a9f2b6-86d5-474e-b1f5-cd0617ff6e0e"),
                            CountryImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/2560px-Flag_of_India.svg.png",
                            Description = "The Chinese film industry is one of the largest in the world, known for its blend of traditional storytelling and modern blockbusters. It boasts a massive domestic audience, government support, and global recognition, with hits like The Wandering Earth and directors such as Zhang Yimou. China's industry continues to expand, influencing both local culture and the global market.",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("df078226-92ab-4336-b928-0562a9ad56ef"),
                            CountryImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/800px-Flag_of_the_People%27s_Republic_of_China.svg.png",
                            Description = "India's film industry, known as Bollywood and regional cinema hubs like Tollywood and Kollywood, is the largest in the world by volume, producing over 1,500 films annually. Renowned for its vibrant musicals, emotional storytelling, and diverse languages, it caters to a massive domestic audience and a growing global fanbase. Iconic productions like RRR and Dangal highlight its increasing international influence.",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("d183fd11-6e4f-4bea-8795-79b479e6dcf4"),
                            CountryImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png",
                            Description = "The UK film industry is renowned for its rich cinematic heritage and world-class talent, contributing significantly to global cinema. Known for iconic franchises like James Bond and Harry Potter, it blends independent filmmaking with major international co-productions. Supported by institutions like the British Film Institute (BFI), it remains a hub for creativity and innovation in film.",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("e69a6a92-05bc-43cb-b23b-21536b250c2e"),
                            CountryImageUrl = "https://cdn.britannica.com/82/682-050-8AA3D6A6/Flag-France.jpg",
                            Description = "The French film industry, often regarded as the birthplace of cinema, is celebrated for its artistic innovation and rich storytelling tradition. Known for iconic directors like François Truffaut and Jean-Luc Godard, it produces a mix of auteur-driven films and popular comedies. Supported by strong government funding, France remains a global leader in cinematic culture and hosts the prestigious Cannes Film Festival.",
                            Name = "France"
                        });
                });

            modelBuilder.Entity("MovieApp.DataModels.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("DirectorImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamousMovies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46b852dc-b9d8-4f2e-a422-9d891e97920e"),
                            Description = "Christopher Nolan (born July 30, 1970) is a visionary British-American filmmaker celebrated for his innovative storytelling, complex narratives, and technical mastery.",
                            DirectorImageUrl = "https://m.media-amazon.com/images/M/MV5BNjE3NDQyOTYyMV5BMl5BanBnXkFtZTcwODcyODU2Mw@@._V1_FMjpg_UX1000_.jpg",
                            FamousMovies = "Oppenheimer (2023), Tenet (2020), Dunkirk (2017)",
                            FirstName = "Christopher",
                            Surname = "Nolan"
                        },
                        new
                        {
                            Id = new Guid("0f1a5321-cc6d-4eaf-ae57-ebcb41ce49d6"),
                            Description = "Rajkumar Hirani (born November 20, 1962) is a renowned Indian filmmaker celebrated for his ability to blend humor, emotion, and social commentary.",
                            DirectorImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/44/Rajkumar_Hirani_2014.jpg",
                            FamousMovies = "Dunki (2023), PK (2014), Munna Bhai M.B.B.S. (2003)",
                            FirstName = "Rajkumar",
                            Surname = "Hirani"
                        },
                        new
                        {
                            Id = new Guid("b9f76a01-f545-452f-8532-9662c7859c5d"),
                            Description = "Frank Darabont (born January 28, 1959) is an acclaimed American filmmaker known for adapting emotionally resonant films, particularly from Stephen King's works.",
                            DirectorImageUrl = "https://m.media-amazon.com/images/M/MV5BNjk0MTkxNzQwOF5BMl5BanBnXkFtZTcwODM5OTMwNA@@._V1_.jpg",
                            FamousMovies = "The Mist (2007), The Shawshank Redemption (1994), The Green Mile (1999)",
                            FirstName = "Frank",
                            Surname = "Darabont"
                        },
                        new
                        {
                            Id = new Guid("bbc53dfd-df68-4d63-82e3-d0f320a94e13"),
                            Description = "Andrei Tarkovsky (April 4, 1932 – December 29, 1986) was a legendary Soviet filmmaker known for his poetic and visually stunning films.",
                            DirectorImageUrl = "https://images.mubicdn.net/images/cast_member/1039/cache-4-1337461025/image-w856.jpg",
                            FamousMovies = "The Sacrifice (1986), Nostalghia (1983), Stalker (1979)",
                            FirstName = "Andrei",
                            Surname = "Tarkovsky"
                        },
                        new
                        {
                            Id = new Guid("46a23ca5-cbe6-4fd2-8b3a-3409b3be6d19"),
                            Description = "Stanley Kubrick (July 26, 1928 – March 7, 1999) was an iconic filmmaker known for his innovative techniques and mastery across genres.",
                            DirectorImageUrl = "https://www.all-about-photo.com/images/photographer/K/PHOT-stanley-kubrick-30.jpg",
                            FamousMovies = "The Shining (1980), 2001: A Space Odyssey (1968), Eyes Wide Shut (1999)",
                            FirstName = "Stanley",
                            Surname = "Kubrick"
                        });
                });

            modelBuilder.Entity("MovieApp.DataModels.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Casts")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MovieImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Production")
                        .IsRequired()
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dad92977-3e9f-4496-a404-cf55f3ab77a3"),
                            Casts = "Marilyn Burns, Allen Danziger, Paul A. Partain, William Vail, Teri McMinn",
                            Country = "United States of America",
                            Description = "A chain-saw wielding his category of cannibals and killer hunts and terrorized five friends visiting their grandfather's house from the country",
                            Duration = 83,
                            Genre = "Horror",
                            MovieImageUrl = "https://waxworkrecords.com/cdn/shop/files/TCSM-Game_Cover_1080x.jpg?v=1691613262.jpg",
                            Production = "New Line Cinema, Vortex",
                            ReleaseDate = new DateTime(1974, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Texas Chain Saw Massacre"
                        },
                        new
                        {
                            Id = new Guid("49d08a34-4a7d-4a81-ad37-28dd0a6bcf60"),
                            Casts = "Ellen Burstyn, Jason Miller, Max von Sydow, Linda Blair, Lee J. Cobb",
                            Country = "United States of America",
                            Description = "As strange events befall the place of Georgetown 12-year-old Regan MacNeil begins to adapt an explicit personality. Her mum ultimately turns into her hope, and becomes torn between superstition and science at a desperate bid to save her daughter: a priest who's currently fighting along with his own faith Father Damien Karras.",
                            Duration = 122,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/I/716Gr-3e6rL._AC_UF894,1000_QL80_.jpg.jpg",
                            Production = "Hoya Productions, Warner Bros. Pictures",
                            ReleaseDate = new DateTime(1973, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = new Guid("e252724e-8955-4427-8765-4ec8f98dd3a0"),
                            Casts = "Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers, Barry Nelson",
                            Country = "United Kingdom, United States of America",
                            Description = "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, together with his wife Wendy and their son Danny, has to live isolated. But they aren't ready for the insanity that lurks within.",
                            Duration = 144,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Production = "Hawk Films, Peregrine, Warner Bros. Pictures, Producers Circle",
                            ReleaseDate = new DateTime(1980, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("eb2df1ed-4090-4c34-b10f-eec1148e6803"),
                            Casts = "Patrick Wilson, Vera Farmiga, Lili Taylor, Ron Livingston, Mackenzie Foy",
                            Country = "United States of America",
                            Description = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by way of a presence in their own farm house. The Warrens are trapped in the terrifying case of his or her lifetimes.",
                            Duration = 112,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/I/5147F62RsML._AC_UF1000,1000_QL80_.jpg",
                            Production = "New Line Cinema, The Safran Company, Evergreen Media Group",
                            ReleaseDate = new DateTime(2013, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = new Guid("68eea93c-ab23-48b0-bcd6-b56fb5878a43"),
                            Casts = "Naomi Watts, Martin Henderson, David Dorfman, Brian Cox, Jane Alexander",
                            Country = "Japan, United States of America",
                            Description = "It seemed leading to a cellular mobile cell phone call foretelling the viewer's death in exactly seven days. Like a newspaper reporter, Rachel Keller was clearly skeptical of this story, until four teenagers all met with mysterious deaths exactly 1 week. Allowing her investigative curiosity to get the better of her, Rachel tracks down the video... and watches it. She has just seven days to unravel the mystery of the Ring.",
                            Duration = 115,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/M/MV5BMTY2ODc2NTQ2OF5BMl5BanBnXkFtZTYwNzA4OTU3._V1_.jpg",
                            Production = "BenderSpink, Parkes+MacDonald Image Nation, DreamWorks",
                            ReleaseDate = new DateTime(2002, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Ring"
                        },
                        new
                        {
                            Id = new Guid("99f80b53-dd21-443b-b625-ade19d74678a"),
                            Casts = "Beatrice Rubica, Lili Bordán, Jared Morgan, Lynnette Gaza, David Horovitch",
                            Country = "United States of America",
                            Description = "The Vatican sends a priest with a past and a novitiate on the brink of her final cries to explore Every time a nun in a abbey at Romania takes her own life. They uncover the order secret. Risking not only their lives but their faith and their very souls, they face a malevolent force at the kind of the same demonic nun that terrorized audiences at\"The Conjuring 2\" as the abbey gets to be a dreadful battle ground between the alive and the damned.",
                            Duration = 96,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/I/61QaDRRcTrL._AC_UF894,1000_QL80_.jpg.jpg",
                            Production = "New Line Cinema, Atomic Monster, The Safran Company",
                            ReleaseDate = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Nun"
                        },
                        new
                        {
                            Id = new Guid("ba1a0b02-cd0a-4961-8d42-d940fb220a96"),
                            Casts = "Ethan Hawke, Juliet Rylance, Vincent D'Onofrio, James Ransone, Fred Dalton Thompson",
                            Country = "United States of America",
                            Description = "Footage helps a truecrime novelist realize a household has been killed inside his new residence, though his discoveries put his family.",
                            Duration = 110,
                            Genre = "Horror",
                            MovieImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaS6dDLX1WEgUs2vVn9JhE-MDaXF3BDMFdIw&s.jpg",
                            Production = "Automatik Entertainment, Blumhouse Productions, Alliance Films, IM Global, Possessed Pictures",
                            ReleaseDate = new DateTime(2012, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sinister"
                        },
                        new
                        {
                            Id = new Guid("d5165433-648b-431f-866f-65d1d681eec7"),
                            Casts = "Maika Monroe, Keir Gilchrist, Daniel Zovatto, Olivia Luccardi, Lili Sepe",
                            Country = "United States of America",
                            Description = "To get 19-year-old Jay, autumn should be all about boys school and weekends out at the lake. But a seemingly innocent encounter gives her inescapable sense that some one , or something, is after her and turns sour. Up against this weight, Jay and her friends must find a means to flee.",
                            Duration = 101,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/M/MV5BNGZiYWRiYjAtODU0NS00YzAzLTk2MzQtZGVlMzVjM2M3MGQ3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg.jpg",
                            Production = "Two Flints, Northern Lights Films, Animal Kingdom",
                            ReleaseDate = new DateTime(2014, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "It Follows"
                        },
                        new
                        {
                            Id = new Guid("7c86acbb-40ff-43d9-aea7-af7955144b20"),
                            Casts = "Essie Davis, Noah Wiseman, Hayley McElhinney, Daniel Henshall, Barbara West",
                            Country = "Canada, Australia",
                            Description = "A single mommy, harassed with her husband's brutal death , struggles with her son's anxiety about a monster lurking in your house, but soon discovers a menacing presence all.",
                            Duration = 94,
                            Genre = "Horror",
                            MovieImageUrl = "https://silver.afi.com/CDN/Image/Entity/FilmPosterGraphic/f-0100004762?width=48&height=48.jpg",
                            Production = "Screen Australia, Smoking Gun Productions, Causeway Films, South Australian Film Corporation, Entertainment One",
                            ReleaseDate = new DateTime(2014, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Babadook"
                        },
                        new
                        {
                            Id = new Guid("47d3051b-c9a4-4bd5-8a02-4554add1a0d3"),
                            Casts = "Nicole Kidman, Christopher Eccleston, Alakina Mann, James Bentley, Eric Sykes",
                            Country = "Spain, United States of America, France, Italy",
                            Description = "Grace is really actually a woman who resides in a older house kept dark because her two children have a rare sensitivity. When your household begins to suspect your house is haunted, Grace fights to protect her kids at any cost at the face of strange events and disturbing fantasies.",
                            Duration = 101,
                            Genre = "Horror",
                            MovieImageUrl = "https://m.media-amazon.com/images/I/61cVO6WvabL._AC_UF894,1000_QL80_.jpg",
                            Production = " Cruise/Wagner Productions, Canal+, Sogecine, Las Producciones del Escorpion, Lucky Red, Dimension Films, Miramax",
                            ReleaseDate = new DateTime(2001, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Others"
                        });
                });

            modelBuilder.Entity("MovieApp.DataModels.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("MovieOrShow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a845e762-7461-42b9-af77-b9079f74b92e"),
                            CharacterName = "Michael Scofield",
                            Description = "'Sometimes, the only way to truly escape the past is to keep moving forward.'",
                            MovieOrShow = "Prison Break"
                        },
                        new
                        {
                            Id = new Guid("2310a54a-a66d-4869-98d0-f9c5db538cd8"),
                            CharacterName = "Tyrion Lannister",
                            Description = "“Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.”",
                            MovieOrShow = "Game og Thrones"
                        },
                        new
                        {
                            Id = new Guid("2c6efb15-bfd8-4ae6-8e15-2ad56731e849"),
                            CharacterName = "Fernando Sucre",
                            Description = "“When you love someone, you’ll do anything for them. Even if it means breaking every rule in the book.”",
                            MovieOrShow = "Prison Break"
                        },
                        new
                        {
                            Id = new Guid("5e7f6bb9-2625-4136-aea8-d41a9afdbedf"),
                            CharacterName = "Yoda",
                            Description = "“Do, or do not. There is no try.”",
                            MovieOrShow = "Star Wars"
                        },
                        new
                        {
                            Id = new Guid("38133634-8b30-4e74-96ce-663e5c3908ed"),
                            CharacterName = "Forest Gump",
                            Description = "“Life is like a box of chocolates. You never know what you’re gonna get.”",
                            MovieOrShow = "Forest Gump"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
